<?php
require_once('functions/global.php');
require_once('functions/forum.php');
require_once('classes/class.user.php');
require_once('classes/class.lobby.php');
require_once('classes/class.server.php');
require_once('classes/class.mumble.php');
require_once('classes/class.banpoint.php');
require_once('classes/class.ClientSocket.php');
?>