		<div id="content" class="big_panel user_center">
			<ul class="nav_panel">
				<li><a href="index.html">Home</a></li>
				<li class="current"> &raquo; Admincenter</li>

			</ul>
			<div class="panel">
				<ul>
					<li>&raquo; Forum</li>
					<li><a href="#">&raquo; Adminlist</a></li>
					<li><a href="#">&raquo; Banlist</a></li>
				</ul>
			</div>
			<div class="panel" style="width: 700px">
				<h1>New Topic:</h1>
					<form method="post">
						<label>Name</label><input type="text" name="name" size="40" />
						<label>Message</label><textarea rows="7" cols="40" name="message" style="float: left;"></textarea>
						<input type="submit" value="Submit" class="button small" style="clear: left;float: left;" />
					</form>
			</div>
		</div>
	</div>
</body>
</html>
