<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title>TF2 Matchmaking System</title>
    <link href="theme/style.css" rel="stylesheet" type="text/css" />
    <link href="theme/uniform.default.css" rel="stylesheet" type="text/css" />
    <script src="theme/js/jquery.js" type="text/javascript"></script>
    <script src="theme/js/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="theme/js/main.js" type="text/javascript"></script>
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1100163-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
    <div id="background_image"></div>
    <div id="wrapper">
        <div id="header">
            <a href="index.php" id="logo">TF2 Matchmaking System</a>
        </div>